### PR TITLE
Add graphiql when mix.env is dev

### PR DESCRIPTION
**Pull request by IvanIvanoff**

### CODE REVIEW

**Comment by valo** [comment]
I would recommend using the graphiql app, as it allows to set headers in the requests. With the web version of graphiql you won't be able to make authenticated requests to the GQL API.

**Comment by valo** [comment]
https://github.com/skevy/graphiql-app

**Comment by IvanIvanoff** [comment]
That's actually `graphiql-workspace` [graphiql-workspace](https://github.com/OlegIlyenko/graphiql-workspace)
It allows adding custom headers.

**Comment by valo** [comment]
Cool! Seems like I tried only the simple interface, which didn't allow that. Let's use this.

**Comment by valo** [comment]
Cool! Seems like I tried only the simple interface, which didn't allow that. Let's use this.

**Pull request merged**
