### PR TITLE
Add API specs for social metrics precomputed in CH

### PR DESCRIPTION
**Pull request by apozdeyev**
## Changes

Added API specs for social metrics precomputed in CH:

1. social_volume_total
2. social_dominance_total
3. sentiment_volume_consumed_total
4. sentiment_positive_total
5. sentiment_negative_total
6. sentiment_balance_total

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have tried to find clearer solution before commenting hard-to-understand parts of code
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by apozdeyev** [comment]
@IvanIvanoff I added API specs, but as I understand it also needs to exclude these metrics from `social_data/metric_adapter.ex`?

**Comment by apozdeyev** [comment]
> @IvanIvanoff I added API specs, but as I understand it also needs to exclude these metrics from `social_data/metric_adapter.ex`?

@tspenov Hi! Maybe you can help me to finish this PR?

**Comment by tspenov** [comment]
@apozdeyev
🎉  Nice work on this. 

* The new metrics from `.json` file override the existing ones so results are from the new metrics.
* I don't see `social_volume` metric in `intraday_metrics` table on stage. The others work.
* I'll push a fix to the tests - I suppose they are failing because they test the old implementation

**Comment by apozdeyev** [comment]
> @apozdeyev
> 🎉 Nice work on this.

Thanks!

>     * The new metrics from `.json` file override the existing ones so results are from the new metrics.

Good!

>     * I don't see `social_volume` metric in `intraday_metrics` table on stage. The others work.

Hmm, I can request it now. What query did you use? 

<details>
<summary>Here is my query</summary>
<p>

```sql
SELECT 
    dt, 
    value
FROM default.intraday_metrics
WHERE asset_id in 
(
    SELECT
        asset_id
    FROM
        default.asset_metadata
    WHERE 
        name == 'bitcoin'
)
AND metric_id in 
(
    SELECT
        metric_id
    FROM
        default.metric_metadata
    WHERE 
        name == 'social_volume'
)
ORDER BY dt DESC
LIMIT 1000
```

</p>
</details>  




>     * I'll push a fix to the tests - I suppose they are failing because they test the old implementation
Now it works:thumbsup:

**Review by tspenov — APPROVED** [review]

**Pull request merged**
