### PR TITLE
Add Flow and Balance per Label and Owner metrics

### PR DESCRIPTION
**Pull request by ninjascant**
## Changes

* Add `inflow_per_label_and_owner`, `outflow_per_label_and_owner` and `balance_per_owner` metric APIs
* Change `labelled_exchange_balance` API name to `balance_per_label_and_owner_delta` for a clearer naming
Requests:
```graphql
{
          
   a: getMetric(metric: "inflow_per_label_and_owner") {
     timeseriesData(
      selector: { slug: "ethereum", label: "eth2stakingcontract"}
      from: "2020-09-06T00:00:00Z"
      to: "2020-12-09T00:00:00Z"
      interval: "1d"
    ) {
      datetime
      value
    }
  }  
   b: getMetric(metric: "outflow_per_label_and_owner") {
     timeseriesData(
      selector: { slug: "ethereum", label: "decentralized_exchange", owner: "uniswap"}
      from: "2020-09-06T00:00:00Z"
      to: "2020-12-09T00:00:00Z"
      interval: "1d"
    ) {
      datetime
      value
    }
  }  
    c: getMetric(metric: "balance_per_label_and_owner_delta") {
     timeseriesData(
      selector: { slug: "ethereum", label: "centralized_exchange"}
      from: "2020-09-06T00:00:00Z"
      to: "2020-12-09T00:00:00Z"
      interval: "1d"
    ) {
      datetime
      value
    }
  } 
    d: getMetric(metric: "balance_per_owner") {
     timeseriesData(
      selector: { slug: "ethereum", label: "centralized_exchange", owner: "coinbase"}
      from: "2020-09-06T00:00:00Z"
      to: "2020-12-09T00:00:00Z"
      interval: "1d"
    ) {
      datetime
      value
    }
  } 
```

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have tried to find clearer solution before commenting hard-to-understand parts of code
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Partysun** [comment]
@Snedashkovsky Pls add example of usages to the description of this PR. You can see an example here - https://github.com/santiment/sanbase2/pull/2399

**Comment by Snedashkovsky** [comment]
@Partysun Updated

**Review by tspenov — APPROVED** [review]

**Comment by tspenov** [comment]
@Snedashkovsky But I think the metric names in the description are different than those in the yaml.

**Review by IvanIvanoff — APPROVED** [review]

**Comment by Snedashkovsky** [comment]
@tspenov @IvanIvanoff Updated API names

**Pull request merged**
