### PR TITLE
Fetch the contract info by slug instead of ticker to avoid duplicates

### PR DESCRIPTION
**Pull request by IvanIvanoff**
#### Summary
We now have duplicate tickers that both have coinmarketcap id - that causes troubles.

#### Screenshots
Support both `ticker` and `slug` arguments for smoother transition.

### CODE REVIEW

**Comment by IvanIvanoff** [comment]
I see no problem that the old code will continue to try tickers - we do not have changes in the DB or anything that will make the old code invalid. Or am I missing someting?

**Comment by valo** [comment]
When we deploy the changes the old and the new code will be running at the same time for a while, so we will continue to get the old GQL requests for a while and they will fail because we search by slug and not by ticker in the new code.

**Comment by IvanIvanoff** [comment]
In that case the question is when we can afford that downtime. The problem that this PR solves is observed in 1 or 2 small projects and does not disrupt the work of sanbase - we'll only see the error alerts

**Comment by valo** [comment]
When will the frontend changes happen for this? Shouldn't we add them in this PR so that we ship both frontend and API changes together to production?

**Comment by IvanIvanoff** [comment]
I've updated the PR with support for both old and new behaviour. It should be safe to merge it and make changes to the frontend without having downtime due to caching.

**Pull request merged**
