### PR TITLE
Fix/icons

### PR DESCRIPTION
**Pull request by Partysun**

### CODE REVIEW

**Comment by valo** [comment]
Are you sure about the names? For example here https://sanbase-low.santiment.net we use "Santiment Network Token"

**Comment by valo** [comment]
These names are scraped from https://coinmarketcap.com

**Comment by valo** [comment]
BTW, may be we can use a more stable ID for the icons, like `coinmarketcap_id`. This won't be changing.

**Comment by Partysun** [comment]
Yes, it's more better. I will add mixed stylesheets for icons in next week and add this.

**Pull request merged**
