### PR TITLE
Add word trend score api

### PR DESCRIPTION
**Pull request by tspenov**
#### Summary

```graphql
{
  wordTrendScore(
    word: "trx",
    source: TELEGRAM,
    from: "2018-12-22T00:00:00Z",
    to:"2018-12-24T00:00:00Z",
  ) {
    datetime,
    source,
    score
  }
}
```

```graphql
{
  "data": {
    "wordTrendScore": [
      {
        "datetime": "2018-12-22T08:00:00Z",
        "score": 955.9762635692033,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-22T01:00:00Z",
        "score": 702.8604900070991,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-22T14:00:00Z",
        "score": 463.4801579986572,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-23T01:00:00Z",
        "score": 128.18643119865334,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-24T14:00:00Z",
        "score": 46.573611493031734,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-23T08:00:00Z",
        "score": 43.39397738187617,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-24T08:00:00Z",
        "score": 19.332721224555886,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-23T14:00:00Z",
        "score": 5.028586316999088,
        "source": "TELEGRAM"
      },
      {
        "datetime": "2018-12-24T01:00:00Z",
        "score": 0.9883586380985638,
        "source": "TELEGRAM"
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by IvanIvanoff** [comment]
Why return 
```
 {
        "datetime": "2018-12-22T00:00:00Z",
        "hour": 8,
...
}
```
instead of
```
{
        "datetime": "2018-12-22T08:00:00Z",
...
}
```

**Comment by tspenov** [comment]
I think it will be more convenient for frontend to just return it that way than repack it back in datetime and the frontend to unpack it again

**Comment by IvanIvanoff** [comment]
I think we should avoid sending the complete datetime in multiple fields - it will also be easier for the frontend as `datetime` is the standard in all other queries

**Comment by tspenov** [comment]
yeah, now that I think - it makes more sense to be datetime only cause frontend will plot a graph with it - so they won't need hour as a separate field

**Comment by IvanIvanoff** [comment]
@tspenov you can add a test for a failing case

**Comment by tspenov** [comment]
@IvanIvanoff added

**Pull request merged**
