### PR TITLE
Refactor ProjectCard component

### PR DESCRIPTION
**Pull request by LucoLe**
#### Summary

Changes the ProjectCard component to show a small card in mobile view
initially and after the user clicks on the card it expands to show more
data.

Updates the ProjectsMobile component so the size of each card is
calculated automatically. This allows for having cards with different
sizes and also when the size of the card changes (when the user clicks
on the card) everything updates properly.

[//]: # (#### Related PRs)

[//]: # (#### Additional deploy notes)

#### Screenshots

image

### CODE REVIEW

**Comment by valo** [comment]
Does this also work for the currencies?

**Comment by LucoLe** [comment]
yes

**Comment by Partysun** [comment]
@LucoLe Can we remove 'more' from a small card. All card should be clickable. And remove margin between cards, make them, as a list.

**Comment by LucoLe** [comment]
ok

**Comment by LucoLe** [comment]
but I don't think it's a good idea to remove the margin between the cards. Are you sure we should show it as a list?

**Pull request merged**
