### PR TITLE
add images for new story

### PR DESCRIPTION
**Pull request by GarageInc**
**Summary**

Add images for new story

And why do we store images for frontend app in other repository/backend? It looks strange(as saving all icons here) :-)

### CODE REVIEW

**Comment by haritonasty** [comment]
I'm agree. So uncomfortable

**Comment by IvanIvanoff** [comment]
I'm not quite sure why you store them here instead of s3?

**Comment by haritonasty** [comment]
how load to s3, @IvanIvanoff ? Through insight?

**Comment by IvanIvanoff** [comment]
@haritonasty currently yes. but through s3 we have a distinction between stage and prod. Let's move forward with this PR and think of a long term solution

**Pull request merged**
